apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-deployment
  namespace: dev
  annotations:
      circleci.com/project-id: 545168a5-c1d1-4b79-ba0a-cce9766ab8d7
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-container
        image: dancegep/my-k8s-app:latest
        ports:
        - containerPort: 3000